DROP TABLE IF EXISTS `%TBL_COMMUNITY_ARCHIV%`;
DROP TABLE IF EXISTS `%TBL_COMMUNITY_CONFIG%`;
DROP TABLE IF EXISTS `%TBL_COMMUNITY_GROUPS%`;
DROP TABLE IF EXISTS `%TBL_COMMUNITY_PREPARED%`;
DROP TABLE IF EXISTS `%TBL_COMMUNITY_UG%`;
DROP TABLE IF EXISTS `%TBL_COMMUNITY_USER%`;